[package]
name = "glancr"
version = "0.1.0"
edition = "2021"

[dependencies]
ignore = "0.4"
ratatui = "0.24.0"
crossterm = "0.27.0"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
walkdir = "2.4.0"
fuzzy-matcher = "0.3"
syntect = "5.0"
tui-input = "0.8.0"
bat = "0.24"
grep = "0.2"
